import type { Metadata } from "next";
import { Urbanist, Open_Sans } from "next/font/google";

import "./globals.css";



const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });
const openSans = Open_Sans({ subsets: ["latin"], variable: "--font-open-sans" });

export const metadata: Metadata = {
  title: "ATO Artivista",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${openSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
